name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Chọn phiên bản Python phù hợp

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Đảm bảo rằng bạn đã có requirements.txt hoặc thay thế bằng câu lệnh phù hợp

      - name: Syntax check (lint)
        run: |
          find . -name "*.py" -type f -exec python -m py_compile {} \;

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout main
          git fetch origin
          git merge origin/main
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main
